version: 2
jobs:
  build:
    docker:
      - image: node:6-alpine
    working_directory: ~/mv-lite
    steps:
      - run:
          name: Install SSH & Git
          command: apk add --no-cache make bash git openssh
      - checkout
      - run:
          name: Install dependancies
          command: npm install
      - run:
          name: Run tests
          command: npm test
